language: perl
cache:
  directories:
    # local::lib caching
    - $HOME/perl5
addons:
  apt:
    packages:
      - libgirepository1.0-dev
      - libgtk-3-dev
      - aspell     # for dzil Test::PodSpelling
      - aspell-en  # for dzil Test::PodSpelling
matrix:
  include:
    - perl: "5.16"
      os: linux
      dist: trusty
      sudo: required
    - perl: "5.18"
      env: COVERAGE=1   # enables coverage+coveralls reporting
      os: linux
      dist: trusty
      sudo: required
    - perl: "5.20"
      os: linux
      dist: trusty
      sudo: required
    - perl: "blead"
      os: linux
      dist: trusty
      sudo: required
    - perl: "system"
      os: osx
  allow_failures:
    - perl: blead       # ignore failures for blead perl
before_install:
  - . dev/script/install-native-dep
  - . dev/script/start-xvfb
  - . dev/script/get-aux-repo
  - . dev/script/install-and-test-dist
before_script:
  - . dev/script/run-coverage-xform
