language: perl
cache:
  directories:
    # local::lib caching
    - $HOME/perl5
addons:
  apt:
    packages:
      - libgirepository1.0-dev
      - libgtk-3-dev
      - aspell     # for dzil Test::PodSpelling
      - aspell-en  # for dzil Test::PodSpelling
matrix:
  include:
    - perl: "5.16"
      os: linux
      dist: trusty
      sudo: required
    - perl: "5.18"
      env: COVERAGE=1   # enables coverage+coveralls reporting
      os: linux
      dist: trusty
      sudo: required
    - perl: "5.20"
      os: linux
      dist: trusty
      sudo: required
    - perl: "blead"
      os: linux
      dist: trusty
      sudo: required
  allow_failures:
    - perl: blead       # ignore failures for blead perl
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - git clone https://github.com/project-renard/test-data.git test-data
  - export RENARD_TEST_DATA_PATH="`( cd test-data && pwd )`"
  - eval $(curl https://travis-perl.github.io/init) --auto
